export const OPTIONS_QUERY = "OPTIONS";

export const PREFERENCES_QUERY = "PREFERENCES";

export const HOME_FEED_QUERY = "HOME_FEED";

export const SINGLE_DEAL_QUERY = "SINGLE_DEAL";

export const POPULAR_RESTUARANTS_QUERY = "POPULAR_RESTAURANTS_QUERY";
