export const OPTIONS_QUERY = "OPTIONS";

export const PREFERENCES_QUERY = "PREFERENCES";

export const FEED_QUERY = "FEED_QUERY";

export const SINGLE_DEAL_QUERY = "SINGLE_DEAL";

export const DISCOVER_QUERY = "DISCOVER_QUERY";

export const SINGLE_REST_QUERY = "SINGLE_REST_QUERY";
