export const OPTIONS_QUERY = "OPTIONS";

export const PREFERENCES_QUERY = "PREFERENCES";

export const DEAL_FEED_QUERY = "DEAL_FEED";

export const LOCATION_FEED_QUERY = "LOCATION_FEED";

export const SINGLE_DEAL_QUERY = "SINGLE_DEAL";

export const DISCOVER_QUERY = "DISCOVER";

export const SINGLE_REST_QUERY = "SINGLE_REST";

export const FOLLOWING = "FOLLOWING";

export const FAVOURITES = "FAVOURITES";
