//APP
export const HOME_STACK = {
  ROOT: "HS_ROOT",
  SINGLE_RESTAURANT: "HS_SINGLE_REST",
} as const;

export const ACCOUNT_STACK = {
  ROOT: "AS_ROOT",
  PROFILE: "AS_PROFILE",
  FOLLOWING: "AS_FOLLOWING",
  FAVOURITES: "AS_FAVOURITES",
  SINGLE_RESTAURANT: "AS_SINGLE_REST",
} as const;

export const DISCOVER_STACK = {
  ROOT: "DS_ROOT",
  SINGLE_RESTAURANT: "DS_SINGLE_REST",
  CATEGORY: "DS_CATEGORY",
} as const;

export const FAVOURITES_STACK = {
  ROOT: "FS_ROOT",
  SINGLE_RESTAURANT: "FS_SINGLE_REST",
  FOLLOWING: "FS_FOLLOWING",
} as const;

export type DynamicStack =
  | typeof HOME_STACK
  | typeof DISCOVER_STACK
  | typeof FAVOURITES_STACK
  | typeof ACCOUNT_STACK;

//AUTH
export const AUTH_ROUTES = {
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  SIGN_UP: "SIGN_UP",
  SIGN_IN: "SIGN_IN",
  ADD_DETAILS: "ADD_DETAILS",
  ADD_EMAIL_PASSWORD: "ADD_EMAIL_PASSWORD",
  CONFIRM_EMAIL: "CONFIRM_EMAIL",
  GUEST_FEED: "GUEST_FEED",
} as const;

export const COMMON_ROUTES = {
  PRIVACY_POLICY: "PRIVACY_POLICY",
  //authenticated
  PREFERENCES: "PREFERENCES",
  LOCATION: "LOCATION",
  ADD_CUSTOM_LOCATION: "ADD_CUSTOM_LOCATION",
  //deal
  SINGLE_DEAL: "SINGLE_DEAL",
  //restaurant
  SINGLE_RESTAURANT: "SINGLE_RESTAURANT",
  //
  UPDATE_REQUIRED: "UPDATE_REQUIRED",
  MAINTENANCE_MODE: "MAINTENANCE_MODE",
  //map
  MAP_VIEW: "MAP_VIEW",
  //debug
  DEBUG: "DEBUG",
} as const;
